# Generated by Django 6.0.7 on 2026-08-14 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_add_message_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='message',
            name='idx_message_conversation',
        ),
    ]
