# Generated by Django 6.0.7 on 2026-08-15 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_remove_redundant_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='unread_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
