# Generated by Django 6.0.7 on 2026-07-27 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=50)),
                ('model_name', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('mileage', models.PositiveIntegerField()),
                ('fuel_type', models.CharField(choices=[('petrol', 'بنزینی'), ('diesel', 'دیزلی'), ('hybrid', 'هیبرید'), ('electric', 'برقی'), ('plug_in_hybrid', 'پلاگین هیبرید')], max_length=20)),
                ('transmission', models.CharField(choices=[('automatic', 'اتوماتیک'), ('manual', 'دستی'), ('cvt', 'CVT'), ('semi_automatic', 'نیمه اتوماتیک')], max_length=20)),
                ('body_type', models.CharField(choices=[('sedan', 'سدان'), ('suv', 'شاسی\u200cبلند'), ('hatchback', 'هاچ\u200cبک'), ('crossover', 'کراس\u200cاوور'), ('pickup', 'وانت'), ('coupe', 'کوپه')], max_length=20)),
                ('condition', models.CharField(choices=[('new', 'نو'), ('excellent', 'عالی'), ('good', 'خوب'), ('fair', 'مناسب'), ('needs_repair', 'نیاز به تعمیر')], max_length=20)),
                ('color', models.CharField(choices=[('white', 'سفید'), ('black', 'مشکی'), ('silver', 'نقره\u200cای'), ('gray', 'خاکستری'), ('blue', 'آبی'), ('red', 'قرمز'), ('green', 'سبز'), ('yellow', 'زرد'), ('brown', 'قهوه\u200cای'), ('orange', 'نارنجی'), ('other', 'سایر')], max_length=20)),
                ('city', models.CharField(choices=[('tehran', 'تهران'), ('isfahan', 'اصفهان'), ('mashhad', 'مشهد'), ('tabriz', 'تبریز'), ('shiraz', 'شیراز'), ('karaj', 'کرج'), ('ahvaz', 'اهواز'), ('qom', 'قم'), ('kermanshah', 'کرمانشاه'), ('urmia', 'ارومیه'), ('rasht', 'رشت'), ('zahedan', 'زاهدان'), ('hamedan', 'همدان'), ('yazd', 'یزد'), ('ardabil', 'اردبیل'), ('bandar_abbas', 'بندرعباس'), ('kerman', 'کرمان'), ('sanandaj', 'سنندج'), ('bojnord', 'بجنورد'), ('sari', 'ساری'), ('bushehr', 'بوشهر'), ('arak', 'اراک'), ('zanjan', 'زنجان'), ('qazvin', 'قزوین'), ('khorramabad', 'خرم\u200cآباد'), ('birjand', 'بیرجند'), ('noshehr', 'نوشهر'), ('gorgan', 'گرگان'), ('ilam', 'ایلام'), ('semnan', 'سمنان'), ('kashan', 'کاشان')], max_length=20)),
                ('description', models.TextField()),
                ('is_featured', models.JSONField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='car_images/%Y/%m/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ads.car')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='ads.car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'car')},
            },
        ),
    ]
