# Generated by Django 6.0.7 on 2026-08-03 21:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_car_features_alter_car_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['is_active', '-created_at'], name='ads_car_is_acti_c4f212_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['brand', 'model_name'], name='ads_car_brand_8425fc_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['brand', 'price'], name='ads_car_brand_8fa342_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['city', 'price'], name='ads_car_city_660548_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['is_featured', '-created_at'], name='ads_car_is_feat_480790_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['year'], name='ads_car_year_99ff19_idx'),
        ),
    ]
