# Generated by Django 6.0.7 on 2026-08-04 09:08

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_car_ads_car_is_acti_c4f212_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='car',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='car_search_vector_gin'),
        ),
    ]
