# Generated by Django 6.0.7 on 2026-08-07 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_car_search_vector_car_car_search_vector_gin'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
