# Generated by Django 6.0.7 on 2026-08-07 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_add_view_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='view_count',
        ),
    ]
