# Generated by Django 6.0.7 on 2026-08-08 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_remove_car_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='detail_conditions',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='car',
            name='province',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
