# Generated by Django 6.0.7 on 2026-08-09 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0008_car_detail_conditions_car_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='city',
            field=models.CharField(max_length=20),
        ),
    ]
